esphome:
  name: ducted-toshiba-ac
  friendly_name: ducted_toshiba_AC

esp8266:
  board: esp12e




# Enable logging
logger:
  baud_rate: 0  #disable hardware UART log
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ap_timeout: 180s
    ssid: "Ducted-Toshiba-Ac"
    password: "kakakaka"

captive_portal:

i2c:
  sda: GPIO2
  scl: GPIO14
  scan: True

external_components:
  - source:
      type: git
      url: https://github.com/makusets/esphome-tcc-link

    refresh: 0s 

uart:
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 2400
  parity: EVEN

climate:
  - platform: toshiba_ab
    name: "Ducted Toshiba AC"
    id: ducted_toshiba_ac
    connected:
      name: "Ducted Toshiba AC Connected"
    failed_crcs:
      name: "Ducted Toshiba AC Failed CRCs"
    vent:
      name: "Ducted Toshiba AC Vent Switch" 
    on_data_received:
      - lambda: |-
          ESP_LOGD("TU2C", "Data received: %d bytes", x.size());
    master: 0x00

sensor:
  - platform: bme280_i2c
    temperature:
      name: "Indoor Temperature"
      id: esp_sensor_temp
      oversampling: 1x
    pressure:
      name: "Indoor Pressure"
      id: esp_sensor_pressure
      accuracy_decimals: 0
      oversampling: 1x
    humidity:
      name: "Indoor Humidity"
      id: esp_sensor_humidity
      accuracy_decimals: 0
      oversampling: 2x
    address: 0x76
    update_interval: 30s
    